### ISSUE TITLE
Feature request: Teleport portal to portal

### ISSUE THREAD

**Issue by muniategui** [trentech/ProjectWorlds#99]
I would like to see a new feature added where in /portal create you could specify another existing portal as a destination instead of coordinates, by this you would be able to create portal to portal teleports instead of coordinate based teleport. (Either from portal from same world to another form same  and from portal from diferent world to another world portal the link would be done by portla name)

**Comment by trentech** [comment]
This is the wrong plugin to request this feature, however this request inspired me to create a new plugin. It's now in a position to be tested. I haven't written any docs for it yet...I was attempting to make a tutorial video few nights ago but I don't do video editing so I've so far failed to come up with anything worth watching. 

Building a portal uses the same concept for ProjectPortals. however instead of specifying a location, you will specify the direction player will face exiting the portal. Initially The portal will not do anything when created. You will need to link it another portal after they are built.

ex.

`/portal create portal1 north`
(build the portal as usual executing /portal save when complete)
`/portal create portal2 south`
(build the portal as usual executing /portal save when complete)
```
/portal link portal1 portal2
/portal link portal2 portal1
```

Anyways below are links to dev builds and source. 

Make sure to remove ProjectPortals before installing this plugin

https://trentech.org/jenkins/job/SimplyPortals/
https://github.com/trentech/SimplyPortals
